name: Lint and test

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
        cache: true

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@v0.17.0

    - name: Run goimports and fail if it reports anything
      run: |
        [ -z "$(goimports -l -local github.com/bisgardo/dupe-nukem . | tee /dev/stderr)" ] || false

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.6

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint -min_confidence 1 ./...

  test:
    strategy:
      matrix:
        go-version:
        - "1.17"
        - "1.18"
        - "1.19"
        - "1.20"
        - "1.21"
        - "1.22"
        - "1.23"
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "${{ matrix.go-version }}"
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
