name: Go

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Run goimports and fail if it reports anything
      run: |
        [ -z "$(goimports -l -local github.com/bisgardo/dupe-nukem . | tee /dev/stderr)" ] || false

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint -min_confidence 1 ./...

  test:
    strategy:
      matrix:
        go-version:
        - 1.15
        - 1.16
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
